image: Visual Studio 2022
version: '#{build}'
install:
  - cmd: dotnet tool restore --verbosity normal
build: false
build_script:
  - cmd: dotnet nuke -- build pack push-artifacts --configuration Release
test: false
test_script:
  - cmd: dotnet nuke -- test --configuration Debug
deploy: off

